config/routes.rb
Rails.application.routes.draw do

  resources :rooms do
    resources :documents
  end
  resources :comments

  devise_for :users
  root to: "rooms#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :document
	belongs_to :user
end

app/models/document.rb
class Document < ActiveRecord::Base
	belongs_to :user
	belongs_to :room
	has_many :comments

	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  	validates_attachment_content_type :avatar, :content_type => "application/pdf"
end

app/models/room.rb
class Room < ActiveRecord::Base
	has_many :documents
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :documents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
def index
  	@comments = Comment.all
  end

  def show
  	@comment = Comment.find(params[:id])
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      redirect_to @comment
    else
      render :new
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])

    if @comment.update(comment_params)
      redirect_to @comment
    else
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to root_path, notice: 'comment deleted'
  end

private

  def comment_params
    params.require(:comment).permit(:title)
  end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  def index
    @room = Room.find(params[:room_id])
  	@documents = @room.documents
  end

  def show
  	@document = Document.find(params[:id])
  end

  def new
    @room = Room.find(params[:room_id])
    @document = Document.new(room: @room)
  end

  def create
    @room = Room.find(params[:room_id])
    @document = Document.new(document_params)
    @document.room = @room

    if @document.save
      redirect_to room_document_path(@document.room.id, @document.id)
    else
      render :new
    end
  end

  def edit
    @document = Document.find(params[:id])
  end

  def update
    @room = Room.find(params[:room_id])
    @document = Document.find(params[:id])
    @document.room = @room

    if @document.update(document_params)
      redirect_to room_document_path(@document.room.id, @document.id)
    else
      render :edit
    end
  end

  def destroy
    @document = Document.find(params[:id])
    @document.destroy
    redirect_to root_path, notice: 'document deleted'
  end

private

  def document_params
    params.require(:document).permit(:title, :avatar)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
  	@rooms = Room.all
  end

  def show
  	@room = Room.find(params[:id])
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)

    if @room.save
      redirect_to @room
    else
      render :new
    end
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])

    if @room.update(room_params)
      redirect_to @room
    else
      render :edit
    end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    redirect_to root_path, notice: 'Room deleted'
  end

private

  def room_params
    params.require(:room).permit(:name, :subject)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/documents/_form.html.erb
<%= form_for @document, url: room_documents_path, html:{ multipart: true }  do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <br>
    <%= f.file_field :avatar %>
  	<br>
  	<%= f.submit %>
<% end %>

app/views/documents/edit.html.erb
<%= render 'form' %>

app/views/documents/index.html.erb
<% @documents.each do |document| %>
	<p><%= link_to document.title, room_document_path(document.room.id, document.id) %></p>
<% end %>

<p><%= link_to "Create New Document", new_room_document_path%></p>

app/views/documents/new.html.erb
<%= render 'form' %>

app/views/documents/show.html.erb
<h1><%=@document.title%></h1>
  <%= link_to('View', @document.avatar.url(:original)) %>

 <p><%= link_to "Edit This Document", edit_room_document_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thesis</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= link_to "Home", root_path %>
	<% if user_signed_in? %>
		Hello <%= current_user.first_name %>! <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
    <% else %>
        <%= link_to 'Sign In', new_user_session_path %>
     <% end %>

<%= yield %>

</body>
</html>

app/views/rooms/_form.html.erb
<%= form_for @document, url: room_documents_path, html:{ multipart: true }  do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <br>
    <%= f.file_field :avatar %>
  	<br>
  	<%= f.submit %>
<% end %>

app/views/rooms/index.html.erb
<% @rooms.each do |room| %>
	<p><%= link_to room.name, room_path(room) %></p>
<% end %>

<p><%= link_to "Create New Room", new_room_path%></p>

app/views/rooms/new.html.erb
<%= form_for @room do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
  <br>
    <%= f.label :subject %>
    <%= f.text_field :subject %>
  <br>
  <%= f.submit %>
<% end %>

app/views/rooms/show.html.erb
<h1><%=@room.name%></h1>
<h2><%=@room.subject%></h2>

  <% @room.documents.each do |document| %>
    <p><%= link_to document.title %></p>
  <% end %>
  